units_dict = {"matbench_jdft2d": "(meV/atom) ",
              "matbench_phonons": "(cm^-1) ",
              "matbench_dielectric": "(unitless) ",
              "matbench_log_gvrh": "(log10(GPa)) ",
              "matbench_log_kvrh": "(log10(GPa)) ",
              "matbench_perovskites": "(eV/unit cell) ",
              "matbench_mp_gap": "(eV) ",
              "matbench_mp_e_form": "(eV/atom) ",
              "matbench_mp_is_metal": "",
              "matbench_steels": "(MPa) ",
              "matbench_expt_gap": "(eV) ",
              "matbench_expt_is_metal": "",
              "matbench_glass": ""
            }

des_dict = {"matbench_jdft2d": "exfoliation energy",
            "matbench_phonons": "last phdos peak",
            "matbench_dielectric": "refractive index",
            "matbench_log_gvrh": "base 10 logarithm of the DFT Voigt-Reuss-Hill average shear moduli",
            "matbench_log_kvrh": "base 10 logarithm of the DFT Voigt-Reuss-Hill average bulk moduli",
            "matbench_perovskites": "formation energy",
            "matbench_mp_gap": "PBE band gap",
            "matbench_mp_e_form": "formation energy",
            "matbench_mp_is_metal": "if it is a metal",
            "matbench_steels": "yield strength",
            "matbench_expt_gap": "experiment band gap",
            "matbench_expt_is_metal": "if it is a metal",
            "matbench_glass": "if it is a glass"
            }

# task_input_type, task_type, yeo-johnson_transform
task_type_dict = {"matbench_jdft2d" : ["structure", "regression", True],
            "matbench_phonons"      : ["structure", "regression", True],
            "matbench_dielectric"   : ["structure", "regression", True],
            "matbench_log_gvrh"     : ["structure", "regression", False],
            "matbench_log_kvrh"     : ["structure", "regression", False],
            "matbench_perovskites"  : ["structure", "regression", False],
            "matbench_mp_gap"       : ["structure", "regression", False],
            "matbench_mp_e_form"    : ["structure", "regression", False],
            "matbench_mp_is_metal"  : ["structure", "classification", False],
            "matbench_steels"       : ["composition", "regression", True],
            "matbench_expt_gap"     : ["composition", "regression", False],
            "matbench_expt_is_metal": ["composition", "classification", False],
            "matbench_glass"        : ["composition", "classification", False]
            }

element_name_dict = {
        "H": "hydrogen",
        "He": "helium",
        "Li": "lithium",
        "Be": "beryllium",
        "B": "boron",
        "C": "carbon",
        "N": "nitrogen",
        "O": "oxygen",
        "F": "fluorine",
        "Ne": "neon",
        "Na": "sodium",
        "Mg": "magnesium",
        "Al": "aluminum",
        "Si": "silicon",
        "P": "phosphorus",
        "S": "sulfur",
        "Cl": "chlorine",
        "Ar": "argon",
        "K": "potassium",
        "Ca": "calcium",
        "Sc": "scandium",
        "Ti": "titanium",
        "V": "vanadium",
        "Cr": "chromium",
        "Mn": "manganese",
        "Fe": "iron",
        "Co": "cobalt",
        "Ni": "nickel",
        "Cu": "copper",
        "Zn": "zinc",
        "Ga": "gallium",
        "Ge": "germanium",
        "As": "arsenic",
        "Se": "selenium",
        "Br": "bromine",
        "Kr": "krypton",
        "Rb": "rubidium",
        "Sr": "strontium",
        "Y": "yttrium",
        "Zr": "zirconium",
        "Nb": "niobium",
        "Mo": "molybdenum",
        "Tc": "technetium",
        "Ru": "ruthenium",
        "Rh": "rhodium",
        "Pd": "palladium",
        "Ag": "silver",
        "Cd": "cadmium",
        "In": "indium",
        "Sn": "tin",
        "Sb": "antimony",
        "Te": "tellurium",
        "I": "iodine",
        "Xe": "xenon",
        "Cs": "cesium",
        "Ba": "barium",
        "La": "lanthanum",
        "Ce": "cerium",
        "Pr": "praseodymium",
        "Nd": "neodymium",
        "Pm": "promethium",
        "Sm": "samarium",
        "Eu": "europium",
        "Gd": "gadolinium",
        "Tb": "terbium",
        "Dy": "dysprosium",
        "Ho": "holmium",
        "Er": "erbium",
        "Tm": "thulium",
        "Yb": "ytterbium",
        "Lu": "lutetium",
        "Hf": "hafnium",
        "Ta": "tantalum",
        "W": "tungsten",
        "Re": "rhenium",
        "Os": "osmium",
        "Ir": "iridium",
        "Pt": "platinum",
        "Au": "gold",
        "Hg": "mercury",
        "Tl": "thallium",
        "Pb": "lead",
        "Bi": "bismuth",
        "Po": "polonium",
        "At": "astatine",
        "Rn": "radon",
        "Fr": "francium",
        "Ra": "radium",
        "Ac": "actinium",
        "Th": "thorium",
        "Pa": "protactinium",
        "U": "uranium",
        "Np": "neptunium",
        "Pu": "plutonium",
        "Am": "americium",
        "Cm": "curium",
        "Bk": "berkelium",
        "Cf": "californium",
        "Es": "einsteinium",
        "Fm": "fermium",
        "Md": "mendelevium",
        "No": "nobelium",
        "Lr": "lawrencium",
        "Rf": "rutherfordium",
        "Db": "dubnium",
        "Sg": "seaborgium",
        "Bh": "bohrium",
        "Hs": "hassium",
        "Mt": "meitnerium",
        "Ds": "darmstadtium",
        "Rg": "roentgenium",
        "Cn": "copernicium",
        "Nh": "nihonium",
        "Fl": "flerovium",
        "Mc": "moscovium",
        "Lv": "livermorium",
        "Ts": "tennessine",
        "Og": "oganesson"
        }

